---
- name: Remove opencode.jsonc
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.config/opencode/opencode.jsonc"
    state: absent

- name: Remove global AGENTS.md
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.config/opencode/AGENTS.md"
    state: absent

- name: Remove opencode agents directory
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.config/opencode/agents"
    state: absent
